define
  package sub entity,
  has name,
  plays including_compileunit;

  compileunit sub entity,
  has name,
  has package_name,
  plays importing_class,
  plays containing_class,
  plays included_by_package,
  plays cu_source,
  plays cu_dependency;

  class sub entity,
  plays imported_by_compileunit,
  plays contained_by_compileunit,
  has name;

  name sub attribute, datatype string;
  package_name sub attribute, datatype string;

  import_class sub relationship, relates importing_class, relates imported_by_compileunit;
  include_compileunit sub relationship, relates including_compileunit, relates included_by_package;
  contain_class sub relationship, relates containing_class, relates contained_by_compileunit;
  depend_compileunit sub relationship, relates cu_source, relates cu_dependency;

  compileunit_depend
    when {
      (importing_class:$cu1,imported_by_compileunit:$cl1) isa import_class;
      (containing_class:$cu2,contained_by_compileunit:$cl1) isa contain_class;
    }
    then {
      (cu_source:$cu1, cu_dependency:$cu2) isa depend_compileunit;
    };

